<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Appium.WebDriver">
      <Version>4.3.1</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter">
      <Version>4.4.1</Version>
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework">
      <Version>4.4.1</Version>
    </PackageReference>
  </ItemGroup>
</Project>