<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mp3Mangler.Shared\Mp3Mangler.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TestItems\NerdRockFromTheSun.mp3" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="MSTest" Version="4.4.1" />
  </ItemGroup>
</Project>
