<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FileReader.cs;FileWriter.cs;mp3Dto.cs;Mp3InfoExtractor.cs;Mp3Processor.cs;Mp3TagAndFileInfo.cs" />
    <ProjectReference Include="..\Mp3Mangler.Shared\Mp3Mangler.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2021.3.0" />
  </ItemGroup>
</Project>


