<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FileReader.cs;FileWriter.cs;mp3Dto.cs;Mp3InfoExtractor.cs;Mp3Processor.cs;Mp3TagAndFileInfo.cs" />
    <ProjectReference Include="..\Mp3Mangler.Shared\Mp3Mangler.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2021.3.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.0.0" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Buffers" Version="4.4.0" />
    <PackageReference Include="System.CodeDom" Version="4.4.0" />
    <PackageReference Include="System.Collections.Immutable" Version="1.5.0" />
    <PackageReference Include="System.Memory" Version="4.5.3" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.4.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.3.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.5.3" />
    <PackageReference Include="System.Threading.Channels" Version="4.7.1" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>
</Project>


