﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLModelMusicFiling_ConsoleApp1
{
    public partial class MLModelMusicFiling
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"FirstArtist", @"FirstArtist"),new InputOutputColumnPair(@"FirstAlbumArtist", @"FirstAlbumArtist")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"TagTypes", @"TagTypes"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Title", @"Title"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Album", @"Album"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Comment", @"Comment"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Year", @"Year"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"BeatsPerMinute", @"BeatsPerMinute"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Copyright", @"Copyright"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"FirstPerformer", @"FirstPerformer"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"FirstGenre", @"FirstGenre"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"JoinedArtists", @"JoinedArtists"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"JoinedAlbumArtists", @"JoinedAlbumArtists"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"JoinedPerformers", @"JoinedPerformers"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"JoinedGenres", @"JoinedGenres"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"CreateDate", @"CreateDate"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"FirstArtist",@"FirstAlbumArtist",@"TagTypes",@"Title",@"Album",@"Comment",@"Year",@"BeatsPerMinute",@"Copyright",@"FirstPerformer",@"FirstGenre",@"JoinedArtists",@"JoinedAlbumArtists",@"JoinedPerformers",@"JoinedGenres",@"CreateDate"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"FilePath", @"FilePath"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(l1Regularization:1F,l2Regularization:1F,labelColumnName:@"FilePath",featureColumnName:@"Features"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
