
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModelMusicFiling_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModelMusicFiling.ModelInput sampleData = new MLModelMusicFiling.ModelInput()
            {
                TagTypes = @"Id3v2",
                Title = @"Some Song Title",
                Album = @"Greatest Near Misses",
                BeatsPerMinute = @"0",
                Copyright = @"1965",
                FirstArtist = @"Elvis",
                FirstAlbumArtist = @"Elvis",
                FirstPerformer = @"Elvis",
                FirstGenre = @"Rock",
                JoinedArtists = @"Elvis",
                JoinedAlbumArtists = @"Elvis",
                JoinedPerformers = @"Elvis",
                JoinedGenres = @"Rock; Pop",
                CreateDate = @"06/01/2021 11:12:52",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModelMusicFiling.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual FilePath with predicted FilePath from sample data...\n\n");


            Console.WriteLine($"TagTypes: {sampleData.TagTypes}");
            Console.WriteLine($"Title: {sampleData.Title}");
            Console.WriteLine($"Album: {sampleData.Album}");
            Console.WriteLine($"BeatsPerMinute: {sampleData.BeatsPerMinute}");
            Console.WriteLine($"Copyright: {sampleData.Copyright}");
            Console.WriteLine($"FirstArtist: {sampleData.FirstArtist}");
            Console.WriteLine($"FirstAlbumArtist: {sampleData.FirstAlbumArtist}");
            Console.WriteLine($"FirstPerformer: {sampleData.FirstPerformer}");
            Console.WriteLine($"FirstGenre: {sampleData.FirstGenre}");
            Console.WriteLine($"JoinedArtists: {sampleData.JoinedArtists}");
            Console.WriteLine($"JoinedAlbumArtists: {sampleData.JoinedAlbumArtists}");
            Console.WriteLine($"JoinedPerformers: {sampleData.JoinedPerformers}");
            Console.WriteLine($"JoinedGenres: {sampleData.JoinedGenres}");
            Console.WriteLine($"CreateDate: {sampleData.CreateDate}");
            Console.WriteLine($"FilePath: {@"E:\temp\MUSIC SORTED\Rock\Greatest Near Misses\Elvis\Elvis - Greatest Near Misses - Some Song Title.mp3"}");


            Console.WriteLine($"\n\nPredicted: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
