
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModelMusicFiling_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModelMusicFiling.ModelInput sampleData = new MLModelMusicFiling.ModelInput()
            {
                TagTypes = @"Id3v2",
                Title = @"Aria",
                Album = @"Melt White",
                Comment = @"",
                Year = @"0",
                BeatsPerMinute = @"0",
                Copyright = @"",
                FirstArtist = @"Brass Bed",
                FirstAlbumArtist = @"Brass Bed",
                FirstPerformer = @"Brass Bed",
                FirstGenre = @"Alternative",
                JoinedArtists = @"Brass Bed",
                JoinedAlbumArtists = @"Brass Bed",
                JoinedPerformers = @"Brass Bed",
                JoinedGenres = @"Alternative; Indie",
                CreateDate = @"06/01/2021 11:12:52",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModelMusicFiling.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual FilePath with predicted FilePath from sample data...\n\n");


            Console.WriteLine($"TagTypes: {@"Id3v2"}");
            Console.WriteLine($"Title: {@"Aria"}");
            Console.WriteLine($"Album: {@"Melt White"}");
            Console.WriteLine($"Comment: {@""}");
            Console.WriteLine($"Year: {@"0"}");
            Console.WriteLine($"BeatsPerMinute: {@"0"}");
            Console.WriteLine($"Copyright: {@""}");
            Console.WriteLine($"FirstArtist: {@"Brass Bed"}");
            Console.WriteLine($"FirstAlbumArtist: {@"Brass Bed"}");
            Console.WriteLine($"FirstPerformer: {@"Brass Bed"}");
            Console.WriteLine($"FirstGenre: {@"Alternative"}");
            Console.WriteLine($"JoinedArtists: {@"Brass Bed"}");
            Console.WriteLine($"JoinedAlbumArtists: {@"Brass Bed"}");
            Console.WriteLine($"JoinedPerformers: {@"Brass Bed"}");
            Console.WriteLine($"JoinedGenres: {@"Alternative; Indie"}");
            Console.WriteLine($"FilePath: {@"E:\temp\MUSIC SORTED\Alternative\Brass Bed\Melt White\Brass Bed - Melt White - Aria.mp3"}");
            Console.WriteLine($"CreateDate: {@"06/01/2021 11:12:52"}");


            Console.WriteLine($"\n\nPredicted FilePath: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
